feeds:
  - name: 'AVAX/USD'
    feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
  - name: 'ETH/USD'
    feedId: '0x000359843a543ee2fe414dc14c7e7920ef10f4372990b79d6361cdc0dd1ba782'
chainId: 43113
gasCap: '150000'
interva: '*/30 * * * * *'
priceDelta: '10000000000000000'
chains:
  - {
      'id': 995,
      'name': '🔥 5ireChain',
      'nativeCurrency':
        { 'decimals': 18, 'name': '5ire Token', 'symbol': '5IRE' },
      'rpcUrls': { 'default': { 'http': ['https://rpc.5ire.network'] } },
      'testnet': '',
    }
  - {
      'id': 84532,
      'name': 'Base Sepolia Custom',
      'nativeCurrency':
        { 'decimals': 18, 'name': 'Sepolia Ether', 'symbol': 'ETH' },
      'rpcUrls': { 'default': { 'http': ['https://sepolia.base.org'] } },
      'testnet': 'true',
    }
verifierAddresses:
  - chainId: 995
    address: '0x...'
  - chainId: 84532
    address: '0x...'
targetContracts:
  - feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
    address: '0xfa162F0A25b2C2aA32Ddaacda872B6D7b2c38E47'
    functionName: 'set'
    functionArgs:
      - 'feedId'
      - 'validFromTimestamp'
      - 'observationsTimestamp'
      - 'nativeFee'
      - 'linkFee'
      - 'expiresAt'
      - 'price'
      - 'bid'
      - 'ask'
    abi:
      [
        {
          'inputs':
            [
              {
                'internalType': 'bytes32',
                'name': 'feedId',
                'type': 'bytes32',
              },
              {
                'internalType': 'uint32',
                'name': 'validFromTimestamp',
                'type': 'uint32',
              },
              {
                'internalType': 'uint32',
                'name': 'observationsTimestamp',
                'type': 'uint32',
              },
              {
                'internalType': 'uint192',
                'name': 'nativeFee',
                'type': 'uint192',
              },
              {
                'internalType': 'uint192',
                'name': 'linkFee',
                'type': 'uint192',
              },
              {
                'internalType': 'uint32',
                'name': 'expiresAt',
                'type': 'uint32',
              },
              { 'internalType': 'int192', 'name': 'price', 'type': 'int192' },
              { 'internalType': 'int192', 'name': 'bid', 'type': 'int192' },
              { 'internalType': 'int192', 'name': 'ask', 'type': 'int192' },
            ],
          'name': 'set',
          'outputs': [],
          'stateMutability': 'nonpayable',
          'type': 'function',
        },
      ]
