services:
  # app:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000
  redis:
    image: redis:latest
    container_name: redis-data
    command: redis-server --save 60 1 --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
