services:
  broadcaster:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_HOST=broadcaster-redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - DATASTREAMS_HOSTNAME=${DATASTREAMS_HOSTNAME}
      - DATASTREAMS_WS_HOSTNAME=${DATASTREAMS_WS_HOSTNAME}
      - DATASTREAMS_CLIENT_ID=${DATASTREAMS_CLIENT_ID}
      - DATASTREAMS_CLIENT_SECRET=${DATASTREAMS_CLIENT_SECRET}
    volumes:
      - ./logs:/broadcaster/logs
  broadcaster-redis:
    image: redis:latest
    command: redis-server --save 60 1 --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
networks:
  default:
    driver: bridge