cdcConfig:
  hostname: 'api.testnet-dataengine.chain.link'
  wsHostname: 'ws.testnet-dataengine.chain.link'
  clientID: '...'
  clientSecret: '...'

onChainConfig:
  privateKey: '0x...'
  contractAddress: '0x0a990CFfF29bbd388B29202325b3D81401f3F01C'

clientConfig:
  priceDelta: '10000000000000000'
  intervalMin: 5
  feedId: '0x0003735a076086936550bd316b18e5e27fc4f280ee5b6530ce68f5aad404c796'
